### ISSUE TITLE
[S02] As an Unverified user I should be able to report a suspected kid.

### ISSUE THREAD

**Issue by narimanhesham** [mohamed-mehany/Mafqood#10]
Description: 
The user enters the required fields of a specific form for reporting a suspected kid then clicks on submit button to save his/her post

**Comment by mokhtar93** [comment]
@mohamed-mehany

**Comment by mokhtar93** [comment]
@mohamed-mehany

**Comment by markmorcos** [comment]
@narimanhesham please add translations to the en and ar files.

### SuspectPost
- Model
  - Add a to_s method
  - replace :symbol => "something" with symbol: "something"
- View
  - Add a space after = and after the comma on line 2
  - All strings should be surrounded with double quotation marks.  In special cases, use single quotation marks
  - Assign divs with haml by the selector only, for example, use .class instead of %div.class
  - Add a single space after { and before } and also change :symbol => "something" to symbol: "something"
  - Title in the legend of the fieldset is enough, imo.
  - Replace kid with person in translation files
  - Create a location model which belongs to suspect posts and suspect posts has one location
  - Remove stars \* that exist in labels for required fields
  - Use either placeholders or labels for the form
  - Add a space between the radio buttons and Male/Female
- Controller
  - Use ruby style guide to divide long lines as in the suspect_post_params
