### ISSUE TITLE
S11 : as a verified user i should be able to create a new missing person post

### ISSUE THREAD

**Issue by sharkawy94** [mohamed-mehany/Mafqood#13]
The user clicks on the "new missing" button. Then, a form appears to the user providing a space to enter the details needed for the missing post. The user enters this data successfully and clicks the "submit" button to save this post.

**Comment by markmorcos** [comment]
@sharkawy94 please add translations to the en and ar files.

### MissingPost
- Model
  - Add a to_s method
  - replace :symbol => "something" with symbol: "something"
- View
  - Add a space after = and after the comma on line 2
  - All strings should be surrounded with double quotation marks.  In special cases, use single quotation marks
  - Assign divs with haml by the selector only, for example, use .class instead of %div.class
  - Add a single space after { and before } and also change :symbol => "something" to symbol: "something"
  - Title in the legend of the fieldset is enough, imo.
  - Replace kid with person in translation files
  - Remove stars \* that exist in labels for required fields
  - Use either placeholders or labels for the form
  - Add a space between the radio buttons and Male/Female
- Controller
  - Remove the contents of the index action since it should belong to the new action instead
  - Use ruby style guide to divide long lines as in the missing_post_params
  - Remove the if current_user statement and add before_filter at the top instead
