### ISSUE TITLE
S10CODE I should be able to create a new verified finding post

### ISSUE THREAD

**Issue by ebramsherif** [mohamed-mehany/Mafqood#21]
@markmorcos @mohamed-mehany 

What is yet to be done: translate the error messages

**Comment by markmorcos** [comment]
@ebramsherif please use ruby styling conventions strictly and add translations to en and ar files.

### FindingPost
- Model
  - Add a to_s method
  - Add a single space after a comma
  - Place contact_info, numericality and length on the same line or align the 3 lines with contact_info
  - replace :symbol => "something" with symbol: "something"
  - Validates should be aligned together
  - A tab should be a 2 spaces not the \t character
- View
  - Add a space after = and after the comma on line 1
  - Classes should be defined as css selectors not regular assignment for attributes.
  - Assign divs with haml by only the selector for example, .class instead of %div.class
  - replace :symbol => "something" with symbol: "something"
  - Use either placeholders or labels for the form
  - Use a fieldset with legend and remove background colour for consistency
- Controller
  - Remove the if current_user statement and add before_filter at the top instead
  - Change the finding variables and finding_params method to finding_post and finding_post_params, respectively.
  - Remove any unnecessary spaces and empty lines
  - Use ruby style guide to divide long lines as in the finding_post_params
  - Add a single space after each comma in finding_post_params
  - All strings should be surrounded with double quotation marks.  In special cases, use single quotation marks
- Routes
  - Remove get 'finding_posts/new' as it already exists in the finding_posts resource
  - Add a space between :suspect_posts and :finding_posts

**Comment by ebramsherif** [comment]
@markmorcos  Please close the issue after reviewing changes to the branch
