### ISSUE TITLE
S17: I should be able to edit my missing posts

### ISSUE THREAD

**Issue by sharkawy94** [mohamed-mehany/Mafqood#55]
success demo : The user clicks on the "Edit Post" button, a form appears with the already written fields and the user can modify them then clicks "Save" and the post is edited successfully.

failure demo : I am not logged in so I can't edit my posts, I am trying to edit someone's else post, I submit missing required data or data in incorrect form

**Comment by mohamed-mehany** [comment]
@sharkawy94 check the review of S14 for report of missing_posts_controller also to follow the convention, please use missing_post_params instead of missing_params and also remove the commented is_owner action, also line number 3 is commented, please remove that too
routes.rb file, please remove commented line number 10
20150330185730_adding_columns_in_missing_post_reports file, everything is commented for some reason, either delete it or use it
Gemfile, lines 55 and 56 are the exact same line, please remove one of them

**Comment by mokhtar93** [comment]
v

**Comment by sharkawy94** [comment]
@mokhtar93 updated UMLs S14 & S17

**Comment by ebramsherif** [comment]
@sharkawy94 Where do you check before displaying the edit button that the current user is the post owner?

**Comment by sharkawy94** [comment]
@ebramsherif i added it .
